### ISSUE TITLE
add dark mode

### ISSUE THREAD

**Issue by paulkaefer** [paulkaefer/read-the-world#25]
At the very least, change colors of fonts and add something like:
```CSS
body {background-color: black;}
```
Will this change the background of the SVG object?

Could add a toggle button to the top corner of the page. Use a lightbulb icon/emoji?

I will likely have to change https://paulkaefer.com/stylesheet.css, too.
